services:
  postgres:
    image: postgres:17.2-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "root"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres-data: